OAK <- function() {
  setwd('D:\\6. Lecture\\2. Sophomore_Second\\3.pm_R_Language\\Project')
  Oakland_Athletics <- read.csv('Oakland_Athletics.csv')
  o1 <- ggplot(Oakland_Athletics, aes(YEAR,HR,col=PCT))+labs(title='Oakland Athletics PCT vs HR in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  o2 <- ggplot(Oakland_Athletics, aes(YEAR,SO,col=PCT))+labs(title='Oakland Athletics PCT vs SO in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  o3 <- ggplot(Oakland_Athletics, aes(YEAR,SAC,col=PCT))+labs(title='Oakland Athletics PCT vs SAC in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  o4 <- ggplot(Oakland_Athletics, aes(YEAR,AVG,col=PCT))+labs(title='Oakland Athletics PCT vs AVG in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  o5 <- ggplot(Oakland_Athletics, aes(YEAR,GO.AO,col=PCT))+labs(title='Oakland Athletics PCT vs GO/AO in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  o6 <- ggplot(Oakland_Athletics, aes(YEAR,R,col=PCT))+labs(title='Oakland Athletics vs R in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  o7 <- ggplot(Oakland_Athletics, aes(YEAR, PCT)) +labs(title='Oakland Athletics')+geom_line(color = 9)+geom_point(color = 9)
  o8 <- ggplot(Oakland_Athletics, aes(YEAR, SAC)) +labs(title='Oakland Athletics')+geom_line(color = 13)+geom_point(color = 13)
  o9 <- ggplot(Oakland_Athletics, aes(YEAR, OBP)) +labs(title='Oakland Athletics')+geom_line(color = 10)+geom_point(color = 10)
  setwd('D:\\6. Lecture\\2. Sophomore_Second\\3.pm_R_Language\\Project\\pc')
  ggsave('OAK1.png', plot = o1)
  ggsave('OAK2.png', plot = o2)
  ggsave('OAK3.png', plot = o3)
  ggsave('OAK4.png', plot = o4)
  ggsave('OAK5.png', plot = o5)
  ggsave('OAK6.png', plot = o6)
  ggsave('OAK7.png', plot = o7)
  ggsave('OAK8.png', plot = o8)
  ggsave('OAK9.png', plot = o9)
}