SFG <- function() {
  setwd('D:\\6. Lecture\\2. Sophomore_Second\\3.pm_R_Language\\Project')
  San_Francisco_Giants <- read.csv('San_Francisco_Giants.csv')
  s1 <- ggplot(San_Francisco_Giants, aes(YEAR,HR,col=PCT))+labs(title='San Francisco Giants PCT vs HR in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  s2 <- ggplot(San_Francisco_Giants, aes(YEAR,SO,col=PCT))+labs(title='San Francisco Giants PCT vs SO in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  s3 <- ggplot(San_Francisco_Giants, aes(YEAR,SAC,col=PCT))+labs(title='San Francisco Giants PCT vs SAC in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  s4 <- ggplot(San_Francisco_Giants, aes(YEAR,AVG,col=PCT))+labs(title='San Francisco Giants PCT vs AVG in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  s5 <- ggplot(San_Francisco_Giants, aes(YEAR,GO.AO,col=PCT))+labs(title='San Francisco Giants PCT vs GO/AO in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  s6 <- ggplot(San_Francisco_Giants, aes(YEAR,R,col=PCT))+labs(title='San Francisco Giants vs R in 20 Years')+geom_point(size=5)+scale_colour_gradient(low = 'blue', high = 'red')
  s7 <- ggplot(San_Francisco_Giants, aes(YEAR, PCT)) +labs(title='San Francisco Giants')+geom_line(color = 10)+geom_point(color = 10)
  s8 <- ggplot(San_Francisco_Giants, aes(YEAR, OBP)) +labs(title='San Francisco Giants')+geom_line(color = 11)+geom_point(color = 11)
  s9 <- ggplot(San_Francisco_Giants, aes(YEAR, R)) +labs(title='San Francisco Giants')+geom_line(color = 12)+geom_point(color = 12)
  s10 <- ggplot(San_Francisco_Giants, aes(YEAR, HR)) +labs(title='San Francisco Giants')+geom_line(color = 13)+geom_point(color = 13)
  setwd('D:\\6. Lecture\\2. Sophomore_Second\\3.pm_R_Language\\Project\\pc')
  ggsave('SFG1.png', plot = s1)
  ggsave('SFG2.png', plot = s2)
  ggsave('SFG3.png', plot = s3)
  ggsave('SFG4.png', plot = s4)
  ggsave('SFG5.png', plot = s5)
  ggsave('SFG6.png', plot = s6)
  ggsave('SFG7.png', plot = s7)
  ggsave('SFG8.png', plot = s8)
  ggsave('SFG9.png', plot = s9)
  ggsave('SFG10.png', plot = s10)
}